### ISSUE TITLE
List style overrides font-weight from parent in rich text

### ISSUE THREAD

**Issue by donquixote** [openeuropa/oe_theme#1454]
### Steps to reproduce:
In a site with oe_theme, create content with the following rich text content,
using a text format that allows it.
```html
<table><tr><th>
  <ul><li>List inside table header</li></ul>
</th></tr></table>
```
### Expected behavior
The html will be like this (it is wrapped in `.ecl`):
```html
<div class="ecl">
  <table><tr><th>
    <ul><li>List inside table header</li></ul>
  </th></tr></table>
</div>
```

The text "List inside table header" will be bold, because it is inside a `<th>` tag.

### Actual behavior
(good) Html as above.
(bad) Text is not bold.

### Technical explanation
From ecl-ec-default.css:
```css
.ecl ul:is([class*=ecl-u-]),
.ecl ul:not([class*=ecl-],
[class*=wt-],
[class*=highcharts-]),
.ecl-unordered-list {
 -webkit-padding-start:.75rem;
 color:#404040;
 font:normal normal 400 1rem/1.5rem arial,sans-serif;
 list-style-position:outside;
 margin:0;
 padding-inline-start:.75rem
}
```
The `font: normal normal 400 1rem/1.5rem arial,sans-serif` resets the font-weight from `th`.

### Notes
Actually I am not super sure about the "expected" behavior here.
Is it really so clear that the list should be bold?
On the other hand: Why do we need to override font-weight here? Was this even intended?
