### ISSUE TITLE
Sub-Theme

### ISSUE THREAD

**Issue by kimlop** [openeuropa/oe_theme#393]
Is it possible to create a subtheme?
I followed this guide https://www.drupal.org/docs/8/theming-drupal-8/creating-a-drupal-8-sub-theme-or-sub-theme-of-sub-theme but there are too many errors related to components inheritance

**Comment by brummbar** [comment]
Hey @kimlop , can you show us which errors are you getting?
If I'm not mistaken, other teams already created successfully sub-themes.

**Comment by kimlop** [comment]
Hello, seems that css and js are not loaded. Could you provide an example subtheme (maybe included by default in the oe_theme) ?

**Comment by ademarco** [comment]
For the moment there are no plans to provide a sub-theme, but as far as I know @haringsrob and @kp77 have successfully created one, maybe they could help you.

**Comment by ghost** [comment]
@kimlop , did you load the library in your themename.info.yml?

Here's an example of our subtheme:

```yaml
name: 'Digit QA Theme'
type: theme
description: Custom sub-theme of OpenEuropa Drupal 8 theme
core: 8.x
php: 7.1
# Libraries.
libraries:
  - digit_qa/global-styling
  - oe_theme/component_library_ec
  
base theme: oe_theme

component_library: ec

# Regions.
regions:
  site_top_bar: "Site top bar"
  site_header: "Site header"
  site_header_secondary: "Site header secondary"
  page_header: "Page header"
  navigation: "Navigation"
  content: "Content"
  footer: "Footer"
```

So make sure that you are loading the oe_theme/component_library_ec:

```yaml
libraries:
  - oe_theme/component_library_ec
```

This will load all the component css and js.
