### ISSUE TITLE
Possibility to override ECL templates included by the @ecl-twig namespace

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_theme#528]
Hello,

I know ECL templates are not really meant to be overridden but in some specific cases it could be useful.
At the moment, it is not possible to override, in a subtheme, ECL templates that are included via the `@ecl-twig` namespace in oe_theme.
e.g: `@ecl-twig/button` is called in many oe_theme templates so we can't override it without overriding all the parent templates where it is called.

Maybe the ECL Twig loader could do something like the components 2.x module does with [shared namespaces](https://git.drupalcode.org/project/components/-/blob/8.x-2.x/src/Template/Loader/ComponentsLoader.php)
Which dynamically checks if the current subtheme contains a template override and uses it if found, otherwise it falls back to use the one from the base theme/namespace location.

**Comment by vever001** [comment]
This feature of the components module is not very well documented, but last time I checked it basically works like this:
If we want to override `@foo_namespace/bar.twig` defined in the base theme, we place it in `sub_theme/src/components/bar.twig`.

And `*.info.yml` should look like:
```
# In base_theme.info.yml:
components:
  allow_default_namespace_reuse: true
  namespaces:
    foo_namespace:
      - ./src/components

# In sub_theme.info.yml:
components:
  namespaces:
    foo_namespace:
      - ./src/components
```
